# Basic test fixtures

load("//rules:proto.bzl", "proto_library")

proto_library(
    name = "minimal_proto",
    srcs = ["minimal.proto"],
    visibility = ["PUBLIC"],
)

proto_library(
    name = "types_proto",
    srcs = ["types.proto"],
    options = {
        "go_package": "github.com/org/protobuf-buck2/test/basic/types",
    },
    visibility = ["PUBLIC"],
)
