# Test fixtures for protobuf Buck2 integration

load("//rules:proto.bzl", "proto_library")

proto_library(
    name = "simple_proto",
    srcs = ["simple.proto"],
    options = {
        "go_package": "github.com/org/buck2-protobuf/test/simple",
    },
    visibility = ["PUBLIC"],
)

proto_library(
    name = "complex_proto",
    srcs = ["complex.proto"],
    deps = [":simple_proto"],
    options = {
        "go_package": "github.com/org/buck2-protobuf/test/complex",
    },
    visibility = ["PUBLIC"],
)

proto_library(
    name = "service_proto",
    srcs = ["service.proto"],
    deps = [":simple_proto"],
    options = {
        "go_package": "github.com/org/buck2-protobuf/test/service",
    },
    visibility = ["PUBLIC"],
)
